spring:
  application:
    name: bazarbozorg

  main:
    web-application-type: servlet

  data:
    mongodb:
      uri: mongodb://localhost:27017/bazarbozorg_dev
      authentication-database: admin
      # Optional advanced settings if needed
      # connection-pool:
      #   min-size: 10
      #   max-size: 100
      # connect-timeout: 5000
      # socket-timeout: 5000

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false

server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024

json:
  schema:
    path: classpath:schemas/type-list-schema.json
  folder:
    path: json_output

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

debug: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    com.bazarbozorg: INFO