// Generated by Bazarbozorg TypeList Generator
package com.bazarbozorg.model.types;

import java.lang.Override;
import java.lang.String;
import java.util.UUID;

/**
 * TypeList enum generated from Excel file for Contacttype
 * Generated on: 2025-03-15T17:53:25.3903079
 * @see com.bazarbozorg.model.types.TypeList
 */
public enum ContacttypeTypeList implements TypeList<ContacttypeTypeList> {
  EMAIL("EMAIL", UUID.fromString("3a4b5c6d-7e8f-4a5b-9c7d-1e2f3a4b5c6d")),

  PHONE("PHONE", UUID.fromString("8f7e6d5c-4b3a-2c1d-0e9f-8a7b6c5d4e3f")),

  MOBILE("MOBILE", UUID.fromString("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f")),

  FAX("FAX", UUID.fromString("9d8c7b6a-5f4e-3d2c-1b0a-9f8e7d6c5b4a")),

  ADDRESS("ADDRESS", UUID.fromString("4f5e6d7c-8b9a-0c1d-2e3f-4a5b6c7d8e9f")),

  WEBSITE("WEBSITE", UUID.fromString("7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d")),

  SOCIAL_MEDIA("SOCIAL_MEDIA", UUID.fromString("0c1d2e3f-4a5b-6c7d-8e9f-0a1b2c3d4e5f")),

  OTHER("OTHER", UUID.fromString("6e7f8a9b-0c1d-2e3f-4a5b-6c7d8e9f0a1b"));

  static {
    TypeList.register(ContacttypeTypeList.class);
  }

  private final String code;

  private final UUID id;

  private ContacttypeTypeList(String code, UUID id) {
    this.code = code;
    this.id = id;
  }

  /**
   * Find enum constant by UUID.
   * @param id the UUID to search for
   * @return the matching enum constant or null if not found
   */
  public static ContacttypeTypeList fromId(UUID id) {
    return TypeList.fromId(ContacttypeTypeList.class, id);
  }

  /**
   * Find enum constant by code.
   * @param code the code to search for
   * @return the matching enum constant or null if not found
   */
  public static ContacttypeTypeList fromCode(String code) {
    for (ContacttypeTypeList value : values()) {
      if (value.getCode().equals(code)) {
        return value;
      }
    }
    return null;
  }

  @Override
  public UUID getId() {
    return id;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
