// Generated by Bazarbozorg TypeList Generator
package com.bazarbozorg.model.types;

import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.UUID;

/**
 * TypeList enum generated from Excel file for Country
 * Generated on: 2025-03-15T17:53:25.468822
 * @see com.bazarbozorg.model.types.TypeList
 */
public enum CountryTypeList implements TypeList<CountryTypeList> {
  AFGHANISTAN("AFGHANISTAN", UUID.fromString("91c9e51e-22e3-4867-9f5d-83440a505c1a")),

  ALBANIA("ALBANIA", UUID.fromString("c8d0e4b3-91a1-4f1b-b8f1-7ade22a5c6d8")),

  ALGERIA("ALGERIA", UUID.fromString("f7a2b6d1-3e8c-4a59-9d2e-5bf6c7a8f1e0")),

  @Deprecated
  ANDORRA("ANDORRA", UUID.fromString("e4d5c2b1-9f7e-4d3c-8a6b-1e5f9c8d7a6b")),

  ANGOLA("ANGOLA", UUID.fromString("b8a7c6d5-4e3f-2d1c-0b9a-8f7e6d5c4b3a")),

  ANTIGUA_AND_BARBUDA("ANTIGUA_AND_BARBUDA", UUID.fromString("2d1e0f9c-8b7a-6d5e-4f3c-2b1a0e9d8c7b")),

  ARGENTINA("ARGENTINA", UUID.fromString("5e4d3c2b-1a0f-9e8d-7c6b-5a4f3e2d1c0b")),

  ARMENIA("ARMENIA", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  AUSTRALIA("AUSTRALIA", UUID.fromString("3b2a1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  AUSTRIA("AUSTRIA", UUID.fromString("7c6b5a4f-3e2d-1c0b-9a8d-7e6f5c4d3b2a")),

  AZERBAIJAN("AZERBAIJAN", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  BAHAMAS("BAHAMAS", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  BAHRAIN("BAHRAIN", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  BANGLADESH("BANGLADESH", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  BARBADOS("BARBADOS", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  BELARUS("BELARUS", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  BELGIUM("BELGIUM", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  BELIZE("BELIZE", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  BENIN("BENIN", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f")),

  BHUTAN("BHUTAN", UUID.fromString("7a6b5c4d-3e2f-1d0c-9e8f-7a6b5c4d3e2f")),

  BOLIVIA("BOLIVIA", UUID.fromString("1e0d9f8c-7b6a-5e4f-3c2d-1a0b9c8d7e6f")),

  BOSNIA_AND_HERZEGOVINA("BOSNIA_AND_HERZEGOVINA", UUID.fromString("5a4d3b2c-1e0d-9f8c-7b6a-5e4f3c2d1a0b")),

  BOTSWANA("BOTSWANA", UUID.fromString("9e8f7a6b-5c4d-3e2f-1d0c-9e8f7a6b5c4d")),

  BRAZIL("BRAZIL", UUID.fromString("3a2b1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  BRUNEI("BRUNEI", UUID.fromString("7e6f5a4d-3b2c-1e0d-9f8c-7b6a5e4f3c2d")),

  BULGARIA("BULGARIA", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  BURKINA_FASO("BURKINA_FASO", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  BURUNDI("BURUNDI", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  CAMBODIA("CAMBODIA", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  CAMEROON("CAMEROON", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  CANADA("CANADA", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  CAPE_VERDE("CAPE_VERDE", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  CENTRAL_AFRICAN_REPUBLIC("CENTRAL_AFRICAN_REPUBLIC", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  CHAD("CHAD", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f")),

  CHILE("CHILE", UUID.fromString("7a6b5c4d-3e2f-1d0c-9e8f-7a6b5c4d3e2f")),

  CHINA("CHINA", UUID.fromString("1e0d9f8c-7b6a-5e4f-3c2d-1a0b9c8d7e6f")),

  COLOMBIA("COLOMBIA", UUID.fromString("5a4d3b2c-1e0d-9f8c-7b6a-5e4f3c2d1a0b")),

  COMOROS("COMOROS", UUID.fromString("9e8f7a6b-5c4d-3e2f-1d0c-9e8f7a6b5c4d")),

  CONGO("CONGO", UUID.fromString("3a2b1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  COSTA_RICA("COSTA_RICA", UUID.fromString("7e6f5a4d-3b2c-1e0d-9f8c-7b6a5e4f3c2d")),

  CROATIA("CROATIA", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  CUBA("CUBA", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  CYPRUS("CYPRUS", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  CZECH_REPUBLIC("CZECH_REPUBLIC", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  DENMARK("DENMARK", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  DJIBOUTI("DJIBOUTI", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  DOMINICA("DOMINICA", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  DOMINICAN_REPUBLIC("DOMINICAN_REPUBLIC", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  EAST_TIMOR("EAST_TIMOR", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f")),

  ECUADOR("ECUADOR", UUID.fromString("7a6b5c4d-3e2f-1d0c-9e8f-7a6b5c4d3e2f")),

  EGYPT("EGYPT", UUID.fromString("1e0d9f8c-7b6a-5e4f-3c2d-1a0b9c8d7e6f")),

  EL_SALVADOR("EL_SALVADOR", UUID.fromString("5a4d3b2c-1e0d-9f8c-7b6a-5e4f3c2d1a0b")),

  EQUATORIAL_GUINEA("EQUATORIAL_GUINEA", UUID.fromString("9e8f7a6b-5c4d-3e2f-1d0c-9e8f7a6b5c4d")),

  ERITREA("ERITREA", UUID.fromString("3a2b1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  ESTONIA("ESTONIA", UUID.fromString("7e6f5a4d-3b2c-1e0d-9f8c-7b6a5e4f3c2d")),

  ESWATINI("ESWATINI", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  ETHIOPIA("ETHIOPIA", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  FIJI("FIJI", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  FINLAND("FINLAND", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  FRANCE("FRANCE", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  GABON("GABON", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  GAMBIA("GAMBIA", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  GEORGIA("GEORGIA", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  GERMANY("GERMANY", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f")),

  GHANA("GHANA", UUID.fromString("7a6b5c4d-3e2f-1d0c-9e8f-7a6b5c4d3e2f")),

  GREECE("GREECE", UUID.fromString("1e0d9f8c-7b6a-5e4f-3c2d-1a0b9c8d7e6f")),

  GRENADA("GRENADA", UUID.fromString("5a4d3b2c-1e0d-9f8c-7b6a-5e4f3c2d1a0b")),

  GUATEMALA("GUATEMALA", UUID.fromString("9e8f7a6b-5c4d-3e2f-1d0c-9e8f7a6b5c4d")),

  GUINEA("GUINEA", UUID.fromString("3a2b1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  GUINEA_BISSAU("GUINEA_BISSAU", UUID.fromString("7e6f5a4d-3b2c-1e0d-9f8c-7b6a5e4f3c2d")),

  GUYANA("GUYANA", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  HAITI("HAITI", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  HONDURAS("HONDURAS", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  HUNGARY("HUNGARY", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  ICELAND("ICELAND", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  INDIA("INDIA", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  INDONESIA("INDONESIA", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  IRAN("IRAN", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  IRAQ("IRAQ", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f")),

  IRELAND("IRELAND", UUID.fromString("7a6b5c4d-3e2f-1d0c-9e8f-7a6b5c4d3e2f")),

  ISRAEL("ISRAEL", UUID.fromString("1e0d9f8c-7b6a-5e4f-3c2d-1a0b9c8d7e6f")),

  ITALY("ITALY", UUID.fromString("5a4d3b2c-1e0d-9f8c-7b6a-5e4f3c2d1a0b")),

  JAMAICA("JAMAICA", UUID.fromString("9e8f7a6b-5c4d-3e2f-1d0c-9e8f7a6b5c4d")),

  JAPAN("JAPAN", UUID.fromString("3a2b1c0d-9e8f-7a6b-5c4d-3e2f1a0b9c8d")),

  JORDAN("JORDAN", UUID.fromString("7e6f5a4d-3b2c-1e0d-9f8c-7b6a5e4f3c2d")),

  KAZAKHSTAN("KAZAKHSTAN", UUID.fromString("1a0b9c8d-7e6f-5a4d-3b2c-1e0d9f8c7b6a")),

  KENYA("KENYA", UUID.fromString("5c4d3b2a-1e0f-9d8c-7b6a-5e4f3c2d1a0b")),

  KIRIBATI("KIRIBATI", UUID.fromString("9f8e7d6c-5b4a-3c2d-1b0e-9a8d7f6e5c4b")),

  KUWAIT("KUWAIT", UUID.fromString("3d2c1b0a-9f8e-7d6c-5b4a-3e2d1c0b9f8e")),

  KYRGYZSTAN("KYRGYZSTAN", UUID.fromString("7f6e5d4c-3b2a-1d0c-9e8f-7a6b5c4d3e2f")),

  LAOS("LAOS", UUID.fromString("1d0c9e8f-7a6b-5c4d-3e2f-1d0c9e8f7a6b")),

  LATVIA("LATVIA", UUID.fromString("5e4f3c2d-1a0b-9c8d-7e6f-5a4d3b2c1e0d")),

  LEBANON("LEBANON", UUID.fromString("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d")),

  LESOTHO("LESOTHO", UUID.fromString("3e2d1c0b-9a8d-7f6e-5d4c-3b2a1d0c9e8f"));

  static {
    TypeList.register(CountryTypeList.class);
  }

  private final String code;

  private final UUID id;

  private CountryTypeList(String code, UUID id) {
    this.code = code;
    this.id = id;
  }

  /**
   * Find enum constant by UUID.
   * @param id the UUID to search for
   * @return the matching enum constant or null if not found
   */
  public static CountryTypeList fromId(UUID id) {
    return TypeList.fromId(CountryTypeList.class, id);
  }

  /**
   * Find enum constant by code.
   * @param code the code to search for
   * @return the matching enum constant or null if not found
   */
  public static CountryTypeList fromCode(String code) {
    for (CountryTypeList value : values()) {
      if (value.getCode().equals(code)) {
        return value;
      }
    }
    return null;
  }

  @Override
  public UUID getId() {
    return id;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
