// Generated by Bazarbozorg TypeList Generator
package com.bazarbozorg.model.types;

import java.lang.Override;
import java.lang.String;
import java.util.UUID;

/**
 * TypeList enum generated from Excel file for Local
 * Generated on: 2025-03-15T17:53:25.506822
 * @see com.bazarbozorg.model.types.TypeList
 */
public enum LocalTypeList implements TypeList<LocalTypeList> {
  EN_CA("en_CA", UUID.fromString("3349eb05-d98e-46be-a0b6-a8cd545b46c5")),

  FR_CA("fr_CA", UUID.fromString("872b181d-d0ce-48a2-8730-4961867d9e2c")),

  ES_MX("es_MX", UUID.fromString("2ea4440c-8280-4c9d-b342-36412879940c")),

  PT_BR("pt_BR", UUID.fromString("b76c1ba3-b3a5-4a44-8631-21a1a2cefaba")),

  EN_US("en_US", UUID.fromString("68e4e64b-35ef-4d55-aea0-e07d4aa69f7e")),

  FR_FR("fr_FR", UUID.fromString("13fe32d5-165b-46d2-900f-4114d423d211")),

  DE_DE("de_DE", UUID.fromString("ed9c378d-e552-40a2-90db-052ff4a2b424")),

  IT_IT("it_IT", UUID.fromString("64f16e96-de1c-492c-a009-8b1127b4f6be")),

  ZH_CN("zh_CN", UUID.fromString("3f877fd9-dd00-4c16-8220-09a25e98e20a")),

  JA_JP("ja_JP", UUID.fromString("c5069d36-7f1f-40cd-a65c-5205c00255c3")),

  FA_IR("fa_IR", UUID.fromString("edde0712-d9cb-438a-8f21-d4c9c697fcd3")),

  AR_SA("ar_SA", UUID.fromString("7b47b31e-e671-4218-8dde-5ef8dd91bf91")),

  TR_TR("tr_TR", UUID.fromString("29b7bebd-f9ce-450c-b7aa-21a3213673f6"));

  static {
    TypeList.register(LocalTypeList.class);
  }

  private final String code;

  private final UUID id;

  private LocalTypeList(String code, UUID id) {
    this.code = code;
    this.id = id;
  }

  /**
   * Find enum constant by UUID.
   * @param id the UUID to search for
   * @return the matching enum constant or null if not found
   */
  public static LocalTypeList fromId(UUID id) {
    return TypeList.fromId(LocalTypeList.class, id);
  }

  /**
   * Find enum constant by code.
   * @param code the code to search for
   * @return the matching enum constant or null if not found
   */
  public static LocalTypeList fromCode(String code) {
    for (LocalTypeList value : values()) {
      if (value.getCode().equals(code)) {
        return value;
      }
    }
    return null;
  }

  @Override
  public UUID getId() {
    return id;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
