// Generated by Bazarbozorg TypeList Generator
package com.bazarbozorg.model.types;

import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.UUID;

/**
 * TypeList enum generated from Excel file for Role
 * Generated on: 2025-03-15T17:53:25.5448229
 * @see com.bazarbozorg.model.types.TypeList
 */
public enum RoleTypeList implements TypeList<RoleTypeList> {
  POLICY_ANALYST("Policy Analyst", UUID.fromString("0bc7b4e5-aa01-44d5-a114-8dc46e75c824")),

  SYSTEM_ARCHITECT("System Architect", UUID.fromString("7641965e-ae83-4c1f-b126-a21a908bfa22")),

  @Deprecated
  CYBERSECURITY_ANALYST("Cybersecurity Analyst", UUID.fromString("b80abae7-a9f5-474d-8e75-808739f25b01")),

  QA_ENGINEER("QA Engineer", UUID.fromString("c76751d4-3f79-43bb-b468-13305bc5185f")),

  ACTUARY("Actuary", UUID.fromString("3473be84-999c-42af-aafa-23b36d3b59e1")),

  AUTOMATION_ENGINEER("Automation Engineer", UUID.fromString("ed7f3167-b49e-4e3e-8dcc-f9c4e32f21ce")),

  DATA_ANALYST("Data Analyst", UUID.fromString("dab01602-1a19-4c7b-b665-afa1054f898b")),

  DATABASE_ADMINISTRATOR("Database Administrator", UUID.fromString("89dc866d-92e4-4504-a087-e0b87402600a")),

  INCIDENT_RESPONDER("Incident Responder", UUID.fromString("90b1326d-fa73-4bf1-80f8-fb3a0187f9c8")),

  CLOUD_SOLUTIONS_ARCHITECT("Cloud Solutions Architect", UUID.fromString("28b8101c-e6f2-4018-8491-eedbd6e5d440")),

  SOFTWARE_DEVELOPER("Software Developer", UUID.fromString("e5ebdfdd-0bc1-445e-9f76-b0edac37022d")),

  CUSTOMER_SUCCESS_MANAGER("Customer Success Manager", UUID.fromString("94a402b1-f03f-4711-a3c9-978a74353e94")),

  DEVOPS_ENGINEER("DevOps Engineer", UUID.fromString("0a20f55e-af33-4304-b9e3-986c970d0a30")),

  RISK_MANAGER("Risk Manager", UUID.fromString("16571f12-b9e3-4103-9303-685be047b033")),

  SECURITY_CONSULTANT("Security Consultant", UUID.fromString("325a4f55-8408-44bc-ba64-e41df282a261")),

  UNDERWRITER("Underwriter", UUID.fromString("ddf99346-bfa1-4676-91e4-f6a41ffefa85")),

  CLAIMS_ADJUSTER("Claims Adjuster", UUID.fromString("cba74225-ca33-46f9-a5f7-ddaf4b322e19")),

  CUSTOMER_SUPPORT_SPECIALIST("Customer Support Specialist", UUID.fromString("5e0c71e0-e067-4e61-8549-5f888882d205")),

  OPERATIONS_MANAGER("Operations Manager", UUID.fromString("38f14ea3-a651-4a52-a78c-74e388120856")),

  IT_ADMINISTRATOR("IT Administrator", UUID.fromString("5ebe3de7-3532-4c20-9800-3e4a45ca49fc")),

  AI_SPECIALIST("AI Specialist", UUID.fromString("cde33f9f-3b72-4480-ad39-8134ceed1473")),

  FRAUD_INVESTIGATOR("Fraud Investigator", UUID.fromString("0d0b8bff-9e03-4f0b-b5b9-d19a47f8e8ea")),

  BUSINESS_ANALYST("Business Analyst", UUID.fromString("70ce3726-7034-4f40-8edd-72eef6faf2ab")),

  SUPPORT_MANAGER("Support Manager", UUID.fromString("2c239590-8e9a-4871-aaac-b17dbb72e380")),

  COMPLIANCE_OFFICER("Compliance Officer", UUID.fromString("7bb2cf92-f484-4132-a4bb-885e7a00b7f9")),

  INSURANCE_AGENT("Insurance Agent", UUID.fromString("41f75079-6928-4e70-8c89-1b671f64b780")),

  SERVICE_DESK_ANALYST("Service Desk Analyst", UUID.fromString("3e579903-b52d-47d4-871d-f91661867774")),

  TECHNICAL_ACCOUNT_MANAGER("Technical Account Manager", UUID.fromString("ab965b2d-fd36-4f2c-a098-9f7b81d7bac0")),

  HELP_DESK_TECHNICIAN("Help Desk Technician", UUID.fromString("8278c8ea-3750-4ede-9188-ff8c15861421")),

  NETWORK_ENGINEER("Network Engineer", UUID.fromString("168688b7-e971-4dde-b756-c4f5a544623c")),

  PRODUCT_MANAGER("Product Manager", UUID.fromString("289cff83-751e-4d89-9d07-726a2a5348ce")),

  TECH_SUPPORT_ENGINEER("Tech Support Engineer", UUID.fromString("8fe213ad-5d74-4774-a2cb-b6134228453f"));

  static {
    TypeList.register(RoleTypeList.class);
  }

  private final String code;

  private final UUID id;

  private RoleTypeList(String code, UUID id) {
    this.code = code;
    this.id = id;
  }

  /**
   * Find enum constant by UUID.
   * @param id the UUID to search for
   * @return the matching enum constant or null if not found
   */
  public static RoleTypeList fromId(UUID id) {
    return TypeList.fromId(RoleTypeList.class, id);
  }

  /**
   * Find enum constant by code.
   * @param code the code to search for
   * @return the matching enum constant or null if not found
   */
  public static RoleTypeList fromCode(String code) {
    for (RoleTypeList value : values()) {
      if (value.getCode().equals(code)) {
        return value;
      }
    }
    return null;
  }

  @Override
  public UUID getId() {
    return id;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
